=== PxTools/PCAxis.Sql/PCAxis.Sql/a_codegenerator2/GrandMaster/GrandMaster.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by Jfi (Statistics Norway) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="GrandMaster">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Codes">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Code" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="codeName" type="xs:string" use="required"/>
									<xs:attribute name="defaultCodeValue" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Keywords">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Keyword" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="modelName" type="xs:string" use="required"/>
									<xs:attribute name="optional" type="xs:boolean"/>
									<xs:attribute name="defaultLocalName" type="xs:string">
										<xs:annotation>
											<xs:documentation>normally the uppercased modelName</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Tables">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Table" type="TableType" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="CNMMversion" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="TableType">
		<xs:sequence>
			<xs:element name="Description" type="xs:string"/>
			<xs:element name="Comment" type="xs:string" minOccurs="0"/>
			<xs:element name="Columns" type="ColumnsType"/>
			<xs:element name="generate">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="onlyForDbconfig" minOccurs="0"/>
						<xs:element name="dontMakeRowClasses" minOccurs="0"/>
						<xs:element name="getByPk" minOccurs="0"/>
						<xs:element name="getAllRows" minOccurs="0">
							<xs:complexType>
								<xs:attribute name="key" use="required"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="Dictionary" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="arg" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="id" type="xs:string" use="required"/>
											<xs:attribute name="argClass" type="xs:string" use="optional" default="string"/>
										</xs:complexType>
									</xs:element>
									<xs:element name="is_not_null" minOccurs="0">
										<xs:annotation>
											<xs:documentation>Adds a AND-contraint to the where.</xs:documentation>
										</xs:annotation>
										<xs:complexType>
											<xs:attribute name="columnModelName" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="key" type="xs:string" use="required"/>
								<xs:attribute name="suff" type="xs:string">
									<xs:annotation>
										<xs:documentation>when more than one, to aviod duplicate names</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="List" type="xs:boolean" use="optional" default="false">
									<xs:annotation>
										<xs:documentation>return Dictionary of key and List of rows</xs:documentation>
									</xs:annotation>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="modelName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="tableName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="alias" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Preferably unique!</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="hasSL" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="defaultAlias_lang2" type="xs:string"/>
		<xs:attribute name=" readBySqlDbConfig" type="xs:boolean" use="optional" default="true"/>
	</xs:complexType>
	<xs:complexType name="ColumnType">
		<xs:sequence>
			<xs:element name="Description" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="modelName" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="deviatingDefaultColumnName" use="optional">
			<xs:annotation>
				<xs:documentation>when deviating from upper(modelName)</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="hasSL" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="pk" type="xs:int"/>
		<xs:attribute name="upper" type="xs:boolean"/>
		<xs:attribute name="DateTimeRoundTrip" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>Do a toDateTime.ToString</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="readBySqlDbConfig" type="xs:boolean" use="optional" default="true"/>
		<xs:attribute name="datatype" type="xs:string" use="required"/>
		<xs:attribute name="mandatory" type="xs:string" use="required"/>
		<xs:attribute name="foreignkey" type="xs:string">
			<xs:annotation>
				<xs:documentation>not in use</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="length" use="required"/>
	</xs:complexType>
	<xs:complexType name="ColumnsType">
		<xs:sequence>
			<xs:element name="Column" type="ColumnType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== PxTools/PCAxis.Sql/PCAxis.Sql/a_codegenerator2/Merge_Comments_and_oldMaster/new_master_23.xml
<?xml version="1.0" encoding="utf-8"?>
<GrandMaster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="../GrandMaster/GrandMaster.xsd">
	<Codes>
		<!--Contents.CFPrices -->
		<Code codeName="CFPricesC" defaultCodeValue="C"/>
		<Code codeName="CFPricesF" defaultCodeValue="F"/>
		<!--Contents.StockFA -->
		<Code codeName="StockFAS" defaultCodeValue="S"/>
		<Code codeName="StockFAF" defaultCodeValue="F"/>
		<Code codeName="StockFAA" defaultCodeValue="A"/>
		<!--Contents.Copyright-->
		<Code codeName="Copyright1" defaultCodeValue="1"/>
		<Code codeName="Copyright2" defaultCodeValue="2"/>
		<Code codeName="Copyright3" defaultCodeValue="3"/>
		<!--SpecialCharacter.DataCellFilled-->
		<Code codeName="DataCellFilledOptional" defaultCodeValue="F"/>
		<Code codeName="DataCellFilledValue" defaultCodeValue="V"/>
		<Code codeName="DataCellFilledZero" defaultCodeValue="0"/>
		<!--SubTableVariable.VariableType  -->
		<Code codeName="VariableTypeC" defaultCodeValue="C"/>
		<Code codeName="VariableTypeT" defaultCodeValue="T"/>
		<Code codeName="VariableTypeG" defaultCodeValue="G"/>
		<!--FootNote.MandOpt(M,R), Contents.FootNoteContents, Contents.FootNoteVariable, Contents.FootNoteValue, Contents.FootNoteTime, Value.FootNote, ValuePool.Footnote-->
		<Code codeName="FootnoteM" defaultCodeValue="M"/>
		<Code codeName="FootnoteR" defaultCodeValue="R"/>
		<Code codeName="FootnoteB" defaultCodeValue="B"/>
		<Code codeName="FootnoteN" defaultCodeValue="N"/>
		<!-- Link.LinkFormat -->
		<Code codeName="LinkFormatURL" defaultCodeValue="U"/>
		<Code codeName="LinkFormatMainTable" defaultCodeValue="M"/>
		<!-- Link.LinkType -->
		<Code codeName="LinkTypeTableF" defaultCodeValue="TableF" />
        <Code codeName="LinkTypeTableB" defaultCodeValue="TableB" />
        <Code codeName="LinkTypeTableRel" defaultCodeValue="TableRel" />
        <Code codeName="LinkTypeTableProc" defaultCodeValue="TableProc" />  
        <Code codeName="LinkTypeDok" defaultCodeValue="Dok" />
        <Code codeName="LinkTypeTableRelEx" defaultCodeValue="TableRelEx" />
        <Code codeName="LinkTypeWebsite" defaultCodeValue="Website" />
        <Code codeName="LinkTypeTemasite" defaultCodeValue="Temasite" />
        <Code codeName="LinkTypeAnalys" defaultCodeValue="Analys" />
		<!--Link.LinkPres-->
		<Code codeName="LinkPresDirect" defaultCodeValue="D"/>
		<Code codeName="LinkPresIndirect" defaultCodeValue="I"/>
		<Code codeName="LinkPresBoth" defaultCodeValue="B"/>
		<!--MainTable.PresCategory, Link.PresCategory -->
		<Code codeName="PresCategoryInternal" defaultCodeValue="I"/>
		<Code codeName="PresCategoryPrivate" defaultCodeValue="P"/>
		<Code codeName="PresCategoryPublic" defaultCodeValue="O"/>
		<!--MenuSelection.Presentation-->
		<Code codeName="PresActive" defaultCodeValue="A"/>
		<Code codeName="PresPassive" defaultCodeValue="P"/>
		<Code codeName="PresNo" defaultCodeValue="N"/>
		<!--TimeScale.TimeUnit-->
		<Code codeName="TimeUnitA" defaultCodeValue="Y"/>
		<Code codeName="TimeUnitH" defaultCodeValue="H"/>
		<Code codeName="TimeUnitQ" defaultCodeValue="Q"/>
		<Code codeName="TimeUnitM" defaultCodeValue="M"/>
		<Code codeName="TimeUnitW" defaultCodeValue="W"/>
		<!--ValuePool.ValueTextExists -->
		<Code codeName="ValueTextExistsS" defaultCodeValue="S"/>
		<Code codeName="ValueTextExistsL" defaultCodeValue="L"/>
		<Code codeName="ValueTextExistsB" defaultCodeValue="B"/>
		<Code codeName="ValueTextExistsN" defaultCodeValue="N"/>
		<!--ValuePool.ValuePres, ValueSet.ValuePres-->
		<Code codeName="ValuePresC" defaultCodeValue="C"/>
		<Code codeName="ValuePresT" defaultCodeValue="T"/>
		<Code codeName="ValuePresB" defaultCodeValue="B"/>
		<Code codeName="ValuePresA" defaultCodeValue="A"/>
		<Code codeName="ValuePresS" defaultCodeValue="S"/>
		<!--ValueSet.ValuePres-->
		<Code codeName="ValuePresV" defaultCodeValue="V"/>
		<!--ValuePool.Elimination-->
		<Code codeName="EliminationA" defaultCodeValue="A"/>
		<Code codeName="EliminationN" defaultCodeValue="N"/>
		<!--Grouping.GroupPres -->
		<Code codeName="GroupPresA" defaultCodeValue="A"/>
		<Code codeName="GroupPresI" defaultCodeValue="I"/>
		<Code codeName="GroupPresB" defaultCodeValue="B"/>
		<!--Grouping.Hierarchy -->
		<Code codeName="HierarchyNon" defaultCodeValue="N"/>
		<Code codeName="HierarchyBalanced" defaultCodeValue="B"/>
		<Code codeName="HierarchyUnbalanced" defaultCodeValue="U"/>
		<!-- MainTable.SpecialCharExists-->
		<Code codeName="SpecialSignColumnY" defaultCodeValue="Y"/>
		<Code codeName="SpecialSignColumnN" defaultCodeValue="N"/>
		<Code codeName="SpecialSignColumnE" defaultCodeValue="E"/>
		<!--FootNoteContTime.CellNote, FootNoteContValue.CellNote, MainTableLang2.Status(No),MainTableLang2.Published, Contents.PresCellsZero, Contents.DayAdj,    
          Contents.SeasAdj, SpecialCharacter.AggregPossible;DataCellPres, SpecialCharacter.DataCellFilled(No),TimeScale.TimeScalePres,TimeScale.Regular,
          ValuePool.SortCodeExists-->
		<Code codeName="Yes" defaultCodeValue="Y"/>
		<Code codeName="No" defaultCodeValue="N"/>
		<!--MainTable.TableStatus -->
		<Code codeName="StatusAll" defaultCodeValue="A"/>
		<Code codeName="StatusEmpty" defaultCodeValue="E"/>
		<Code codeName="StatusNew" defaultCodeValue="N"/>
		<Code codeName="StatusMeta" defaultCodeValue="M"/>
		<Code codeName="StatusOrder" defaultCodeValue="O"/>
		<Code codeName="StatusUpdate" defaultCodeValue="U"/>
		<Code codeName="StatusEng" defaultCodeValue="T"/>
		<!--MainTableLang2.Status-->
		<Code codeName="StatusTranslated" defaultCodeValue="T"/>
		<!--MainTablePerson.RolePerson-->
		<Code codeName="RoleMain" defaultCodeValue="M"/>
		<Code codeName="RoleContact" defaultCodeValue="C"/>
		<Code codeName="RoleUpdate" defaultCodeValue="U"/>
		<Code codeName="RoleVerify" defaultCodeValue="V"/>
		<Code codeName="RoleInternationalReporting" defaultCodeValue="V"/>
		<!--FootNote.ShowFootnote -->
		<Code codeName="FootnoteShowS" defaultCodeValue="S"/>
		<Code codeName="FootnoteShowP" defaultCodeValue="P"/>
		<Code codeName="FootnoteShowB" defaultCodeValue="B"/>
	</Codes>
	<Keywords>
		<Keyword modelName="ContentVariable" defaultLocalName="CONTENTVARIABLE"/>
		<Keyword modelName="MenuLevels" defaultLocalName="MENULEVELS"/>
		<Keyword modelName="Macro" defaultLocalName="MACRO"/>
		<Keyword modelName="DataNotAvailable" defaultLocalName = "DATANOTAVAILABLE"/>
        <Keyword modelName="DataNoteSum" defaultLocalName  = "DATANOTESUM"/>
        <Keyword modelName="DataSymbolNIL" defaultLocalName  =  "DATASYMBOLNIL"/>
        <Keyword modelName="DataSymbolSum" defaultLocalName  = "DATASYMBOLSUM"/>
        <Keyword modelName="DefaultCodeMissingLine" defaultLocalName  = "DEFAULTCODEMISSINGLINE"/>
		<!--Keyword modelName="GeoArea" keywordName="GEOOMRADE"/-->
		<!--Keyword modelName="NoOfLanguage" keywordName="NOOFLANGUAGE"/-->
		<!-- <Keyword modelName="PXDescriptionDefault" keywordName="PXDescriptionDefault"/> -->
		<Keyword modelName="PXCodepage" optional="true"/>
		<Keyword modelName="PXDescriptionDefault" optional="true"/>
		<Keyword modelName="PXCharset" optional="true"/>
		<Keyword modelName="PXAxisVersion" optional="true"/>
	</Keywords>
  <Tables CNMMversion="23">
    <Table modelName="Attribute" tableName="ATTRIBUTE" alias="ATT" hasSL="true" defaultAlias_lang2="AT2">
      <Description>The table contains information on the attribute on the observation values.

See further information in the separate document: Attributes in the Nordic SQL Data Model.</Description>
      <Columns>
        <Column modelName="MainTable" pk="1" datatype="varchar" mandatory="True" length="20">
          <Description>Name of the main table to which the attribute is linked.</Description>
        </Column>
        <Column modelName="Attribute" pk="2" datatype="varchar" mandatory="True" length="20">
          <Description>Name of the attribute</Description>
        </Column>
        <Column modelName="AttributeColumn" datatype="varchar" mandatory="True" length="41">
          <Description>Name of the column. The length is set to accommodate future use of prefixes</Description>
        </Column>
        <Column modelName="PresText" hasSL="true" datatype="varchar" mandatory="False" length="25">
          <Description>Presentation text used by the retrieval interface.</Description>
        </Column>
        <Column modelName="SequenceNo" datatype="smallint" mandatory="True" length="">
          <Description>The attributes place in the data table column or the place within the column. The first attribute for a given main table has the value 1.</Description>
        </Column>
        <Column modelName="Description" hasSL="true" datatype="varchar" mandatory="False" length="200">
          <Description>Description of the attribute.</Description>
        </Column>
        <Column modelName="ValueSet" datatype="varchar" mandatory="False" length="30">
          <Description>Name of the value set to which the values are linked.
See further description in table ValueSet.

Can be null â€“ for example if the attribute contains a comment.</Description>
        </Column>
        <Column modelName="ColumnLength" datatype="smallint" mandatory="True" length="">
          <Description>Number of stored characters in the data column.</Description>
        </Column>
        <Column modelName="UserId" readBySqlDbConfig="false" datatype="varchar" mandatory="True" length="20">
          <Description>User identification for the person who has added or updated the current row.</Description>
        </Column>
        <Column modelName="LogDate" readBySqlDbConfig="false" datatype="smalldatetime" mandatory="True" length="">
          <Description>Date and time for the addition or updating of the current row.</Description>
        </Column>
      </Columns>
      <generate>
        <Dictionary key="Attribute" suff="">
          <arg id="MainTable" />
        </Dictionary>
      </generate>
    </Table>
