=== PxTools/PCAxis.Sql/PCAxis.Sql/a_codegenerator2/Comments_in_model/CommentsInModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by Jfi (Statistics Norway) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="CommentsInModel">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Tables">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element ref="Table"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Table">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Description" type="xs:string"/>
				<xs:element name="Columns">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element ref="Column"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Column">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Description" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="colname" type="xs:string" use="required"/>
			<xs:attribute name="datatype" type="xs:string" use="required"/>
			<xs:attribute name="mandatory" type="xs:string" use="required"/>
			<xs:attribute name="primarykey" type="xs:string" use="optional"/>
			<xs:attribute name="foreignkey" type="xs:string" use="optional"/>
			<xs:attribute name="length" use="required"/>
			<xs:attribute name="hasSL" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== PxTools/PCAxis.Sql/PCAxis.Sql/a_codegenerator2/Comments_in_model/CommentsInModel_23.xml
<?xml version="1.0" encoding="UTF-8"?>
<CommentsInModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\kode\assembla12\PCAxis.Sql\codegenerator\Comments_in_model\CommentsInModel.xsd">
	<Tables>
		<Table name="Attribute">
			<Description>The table contains information on the attribute on the observation values.

See further information in the separate document: Attributes in the Nordic SQL Data Model.</Description>
			<Columns>  
				<Column colname="MainTable" primarykey="True" datatype="varchar" length="20" mandatory="True">
					<Description>Name of the main table to which the attribute is linked.</Description>
				</Column>
				<Column colname="Attribute" primarykey="True" datatype="varchar" length="20" mandatory="True">
					<Description>Name of the attribute</Description>
				</Column>
				<Column colname="AttributeColumn" primarykey="False" datatype="varchar" length="41" mandatory="True">
					<Description>Name of the column. The length is set to accommodate future use of prefixes</Description>
				</Column>
				<Column colname="PresText" primarykey="False" datatype="varchar" length="25" mandatory="False" hasSL="True">
					<Description>Presentation text used by the retrieval interface.</Description>
				</Column>
				<Column colname="SequenceNo" primarykey="False" datatype="smallint" length="" mandatory="True">
					<Description>The attributes place in the data table column or the place within the column. The first attribute for a given main table has the value 1.</Description>
				</Column>
				<Column colname="Description" primarykey="False" datatype="varchar" length="200" mandatory="False" hasSL="True">
					<Description>Description of the attribute.</Description>
				</Column>
				<Column colname="ValueSet" primarykey="False" datatype="varchar" length="30" mandatory="False">
					<Description>Name of the value set to which the values are linked.
See further description in table ValueSet.

Can be null – for example if the attribute contains a comment.</Description>
				</Column>
				<Column colname="ColumnLength" primarykey="False" datatype="smallint" length="" mandatory="True">
					<Description>Number of stored characters in the data column.</Description>
				</Column>
				<Column colname="UserId" primarykey="False" datatype="varchar" length="20" mandatory="True">
					<Description>User identification for the person who has added or updated the current row.</Description>
				</Column>
				<Column colname="LogDate" primarykey="False" datatype="smalldatetime" length="" mandatory="True">
					<Description>Date and time for the addition or updating of the current row.</Description>
				</Column>
			</Columns>
		</Table>
		<Table name="ColumnCode">
			<Description>The table is a list and description of all the acceptable codes for the metadata fields in the metadata database.</Description>
			<Columns>
				<Column colname="MetaTable" primarykey="True" datatype="varchar" length="30" mandatory="True">
					<Description>Name of metadata table.</Description>
				</Column>
				<Column colname="ColumnName" primarykey="True" datatype="varchar" length="30" mandatory="True">
					<Description>Name of column.</Description>
				</Column>
				<Column colname="Code" primarykey="True" datatype="varchar" length="10" mandatory="True">
					<Description>Acceptable code alternative.</Description>
				</Column>
				<Column colname="PresText" primarykey="False" datatype="varchar" length="80" mandatory="True" hasSL="True">
					<Description>Descriptive presentation text for code alternatives.</Description>
				</Column>
				<Column colname="UserId" primarykey="False" datatype="varchar" length="20" mandatory="True">
					<Description>User identification for the person who has added or updated the current row.</Description>
				</Column>
				<Column colname="LogDate" primarykey="False" datatype="smalldatetime" length="" mandatory="True">
					<Description>Date and time for the addition or updating of the current row.</Description>
				</Column>
			</Columns>
		</Table>
		
		<Table name="Contents">
			<Description>The table contains information on the content of the data table(s).The content column's name is the same as the name of the corresponding data columns in the data table.</Description>
			<Columns>
				<Column colname="MainTable" primarykey="True" datatype="varchar" length="20" mandatory="True">
					<Description>Name of the main table to which the content columns are linked. See further description in the table MainTable.</Description>
				</Column>
				<Column colname="Contents" primarykey="True" datatype="varchar" length="20" mandatory="True">
					<Description>Name of the data columns in the data table. 
 
A main table's content columns must have unique names within that main table but the same column name can occur in other main tables. 
 
The name should be descriptive, max 20 characters, beginning with a capital letter and should only contain letters (a-z) or numbers. The name can also be broken down using the standard "PascalCase",  i.e. CapitalsAndLowerCase.</Description>
				</Column>
				<Column colname="PresText" primarykey="False" datatype="varchar" length="250" mandatory="True"  hasSL="True">
					<Description>Presentation text used by the retrieval interface when selecting table data and which, after retrieval of a data table, forms the beginning of the table heading. 

The presentation text should be unique within a main table. 

The text should contain information on unit (if not obvious), base time, fixed/ current prices, calendar adjustment and seasonal adjustment. 

The text should begin with a capital letter, should not contain the % symbol and should not be finished with a full-stop.</Description>
				</Column>
				<Column colname="PresTextS" primarykey="False" datatype="varchar" length="80" mandatory="False"  hasSL="True">
					<Description>Short presentation text for content column. Used in retrieval interface, e.g. when selecting table data, or as the column name when table is presented, if the main table has several contents. 

The text should begin with a capital letter, should not contain the % symbol and should not end with a full-stop. 

If there is no text, the field should be NULL.</Description>
				</Column>
				<Column colname="PresCode" primarykey="False" datatype="varchar" length="8" mandatory="True">
					<Description>Presentation code.</Description>
				</Column>
				<Column colname="Copyright" primarykey="False" datatype="char" length="1" mandatory="True">
					<Description>Code for copyright ownership.

All content columns within a main table must belong to the same category, i.e. the same code should be in all the fields.</Description>
				</Column>
				<Column colname="StatAuthority" primarykey="False" datatype="varchar" length="20" mandatory="True">
					<Description>Code for the authority responsible for the statistics (statistical authority). 

All content columns in a main table must belong to the same statistical authority. 

Data is taken from the column OrganizationCode in the table Organization. For a more detailed description, see that table.</Description>
				</Column>
				<Column colname="Producer" primarykey="False" datatype="varchar" length="20" mandatory="True">
					<Description>All content columns in a main table must have the same producer. 

Data is taken from the column OrganizationCode in the table Organization. For a more detailed description, see that table.</Description>
				</Column>
				<Column colname="LastUpdated" primarykey="False" datatype="smalldatetime" length="0" mandatory="False">
					<Description>The date of the most recent update (incl. exact time) of the main table's data tables on the production server. The date remains unchanged when copying over to the external servers. The field is updated automatically by the programs used for loading and updating of data. 
 
If there is no text, the field should be NULL.</Description>
				</Column>
				<Column colname="Published" primarykey="False" datatype="smalldatetime" length="0" mandatory="False">
					<Description>The most recent date for the official release of data, i.e. the date and exact time for the transfer of the main table's data tables to the external servers. The field is updated automatically by the program used for the transfer. 
 
If there is no text, the field should be NULL.</Description>
				</Column>
				<Column colname="Unit" primarykey="False" datatype="varchar" length="60" mandatory="True"  hasSL="True">
					<Description>Unit, e.g. number, currency, index. The given unit should apply to both the storage and the presentation. Details on unit (if not obvious) should also be written in text to the column PresText in the table Contents. 

The unit can also be stored in the content column in the data table. This column is always called Unit and can contain different units for different values. In this case, %DataTable is written in the field unit in the table Contents.</Description>
				</Column>
				<Column colname="PresDecimals" primarykey="False" datatype="smallint" length="0" mandatory="True">
					<Description>The number of decimals that are to be presented in the table presentation when retrievals are made.</Description>
				</Column>
				<Column colname="PresCellsZero" primarykey="False" datatype="char" length="1" mandatory="True">
					<Description>The data table, in principle, only stores cells with values that are not zero. Cells containing zero are only stored if another content column in the same data table has a value other than zero (0) in the corresponding cell. In this field, it should be stated how data cells that are not stored, i.e. cells for which data is missing in all content columns, should be presented. 

Alternatives: 

Y = Yes. The cells are assumed to contain zero. Presented as zero (0). 
N = No. Data cannot be given.
